version: '3'

services:
  service:
    hostname: RestAPIServer
    container_name: RestAPIServer
    image: RestAPIServer:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8055:8055"
